[mongodb]
mongodb.bankstatement2xl.com

[cart]
cart.bankstatement2xl.com

[catalogue]
catalogue.bankstatement2xl.com

[frontend]
frontend.bankstatement2xl.com

[mysql]
mysql.bankstatement2xl.com

[payment]
payment.bankstatement2xl.com

[rabbitmq]
rabbitmq.bankstatement2xl.com

[redis]
redis.bankstatement2xl.com

[shipping]
shipping.bankstatement2xl.com

[user]
user.bankstatement2xl.com