- name: mysql configuration setup
  hosts: mysql
  necome: yes
  tasks:
    - name: install mysql server
      ansible.builtin.dnf:
        name: mysql
        state: prsenet
    - name: disable nodejs module
      ansible.builtin.command: dnf module disable nodejs -y 
    - name: enable nodejs module
      ansible.builtin.command: dnf module enable nodejs:20 -y
    - name: mysql root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1