- name: setup rabbitmq component
  become: yes
  hosts: rabbitmq
  tasks:
    - name: copy rabbitmq repo
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo
    - name: install rabbitmq server
      ansible.builtin.dnf:
        name: rabbitmq-server
        state: present
    - name: enable and start rabbitmq
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: yes
    - name: create rabbitmq users
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        permissions:
          - vhost: /
            configure_priv: .*
            read_priv: .*
            write: .*
        state: present
