- name: redis configuration setup
  hosts: redis
  become: yes
  tasks: 
    - name: disable redis module
      ansible.builtin.command: dnf module disable redis -y 
    - name: enable redis module
      ansible.builtin.command: dnf module enable redis:7 -y 
    - name: install redis
      ansible.builtin.dnf:
        name: redis
        state: present
    - name: replace existing host number to all 
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
    - name: disable protected module
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: 'protected-mode'
        line: protected-mode no
    - name: enable and start redis
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes