- name: configure user setup
  hosts: user
  become: yes
  tasks:
    - name: disable nodejs module
      ansible.builtin.command: dnf module disable nodejs -y 
    - name: enable nodejs module
      ansible.builtin.command: dnf module enable nodejs:20 -y 
    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: create system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app
    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: download user zip file
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /tmp/user.zip
    - name: unzip the user file
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes
    - name: install npm dependencies
      community.general.npm:
        path: /app
    - name: replace user service file 
      ansible.builtin.service:
        src: user.service
        dest: /etc/systemd/system/user.service
    - name: systemctl daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true
    - name: start and enable systemctl
      ansible.builtin.service:
        name: user
        state: started
        enabled: yes
